Add Diurnal Temp Variation Endpoint for Arctic EDS
ua-snap/data-api pull request #242
Opened 2023-01-18 20:39 UTC by charparr

This PR adds an endpoint for mean annual diurnal temperature variation (°C).  You can think of this as the magnitude of the day-night temperature swing you'd experience on average for a year, for a given location and time. The endpoints in this PR are min-mean-max summarized (except for /all/) but diurnal_temp_variation is a top-level route. To test this PR, try a few different queries after setting your Rasdaman backend to Apollo:

http://localhost:5000/diurnal_temp_variation/projected/point/62.0628/-150

http://localhost:5000/diurnal_temp_variation/historical/point/68/-149

http://localhost:5000/diurnal_temp_variation/hp/point/62/-166.1627

http://localhost:5000/diurnal_temp_variation/all/point/69/-151

http://localhost:5000/diurnal_temp_variation/projected/point/65/-145/2070/2099

http://localhost:5000/eds/diurnal_temp_variation/point/65/-147

Also try a CSV query and verify that the CSV makes sense.

This endpoint is very similar to `wet_days_per_year`.

2023-05-03 21:29 UTC, cstephen requested changes
Things look great overall! I've added a few code comments about minor typography and code comment issues.

2023-05-03 21:29 UTC, cstephen commented on routes/diurnal_temp_variation.py
> +            - 2 = minimum summary
These comments don't seem to agree with the code below.

2023-05-03 21:29 UTC, cstephen commented on routes/diurnal_temp_variation.py
> +        for summary_stat in range(0, 3):
How does this relate to the prior mismatch in the prior documentation?

2023-05-03 21:29 UTC, cstephen commented on templates/diurnal_temp_variation/point.html
> +    <td>2006-2100</td>
Use `&ndash;` here instead of hyphen.

2023-05-03 21:29 UTC, cstephen commented on templates/diurnal_temp_variation/point.html
> +  The following query will fetch a complete mean annual diurnal temperature variation (°C) set of data composed of the ERA-Interim historical baseline (1980-2009) and the entire projection range (200
Use `&ndash;` and `&deg;` here.

2023-08-21 18:13 UTC, charparr commented
This PR has become super stale. We're going to consider re-baking extreme diurnal temperature swings into our climate indicator development that will parallel our CMIP6 work. They might be relevant for materials science and engineering (thermal expansion / contraction). However, no one has asked for this specific indicator, the development here was initiated by the presence of this dataset in the original Environmental Atlas.

2023-08-21 18:13 UTC, closed without merging