Adds cache control header fields to keep returned data for 90 days
ua-snap/data-api pull request #283
Opened 2023-07-21 21:40 UTC by BobTorgerson

This PR adds the cache-control headers to our site which can inform upstream caches of how long we would like to cache a file for future reference. When pointed at the Varnish cache for either Rasdaman (maps.earthmaps.io) or the data API (earthmaps.io), it is specifying a max age of 90 days and matches the length of cached time on the Varnish servers.

To test this, you can go to the updated development.earthmaps.io site and look at the returned headers for max age in the cache-control section of the response header: http://development.earthmaps.io/alfresco/veg_type/area/19080309

Closes #73

2023-07-24 17:34 UTC, cstephen requested changes
I've confirmed that the `max-age` cache control header shows up on development.earthmaps.io, and locally too. I added one comment to the code review. Please confirm one way or another if this should be fixed, then this looks good to merge. Thanks!

2023-07-24 17:34 UTC, cstephen commented on fetch_data.py
> +    cache_header = {"Cache-Control": 'max-age=7776000, s-maxage=7776000'}
Should `s-maxage=7776000` be removed from here, too? I don't know one way or the other, just curious!

2023-07-24 19:14 UTC, BobTorgerson commented
@cstephen Go ahead and merge whenever you're ready!

2023-07-26 18:15 UTC, cstephen approved these changes

2023-07-26 18:15 UTC, merged