Adds new temperature endpoint /tas2km to API which queries the 2km historical and projected temperature coverages
ua-snap/data-api pull request #357
Opened 2023-10-02 19:47 UTC by BobTorgerson

This PR adds the new 2km temperature endpoint containing three models (5ModelAvg, GFDL-CM3, and NCAR-CCSM4), two scenarios (RCP 4.5 & RCP 8.5), all months, and all years for both historical (1901-2015) and projected (2006-2100). 

The endpoint is only for point data currently:
localhost:5000/tas2km/point/65/-155

This endpoint has replaced the previous EDS endpoint for temperature which can be seen in:
localhost:5000/eds/temperature/65/-155
localhost:5000/eds/all/65/-155

The coverages for the historical and projected data only exist on Apollo currently so be sure to set your env var appropriately:
export API_RAS_BASE_URL=https://apollo.snap.uaf.edu/rasdaman/

2023-10-03 17:43 UTC, BobTorgerson commented
@charparr @cstephen I think this API update is ready for review!

2023-10-03 19:48 UTC, cstephen requested changes
This new endpoint looks good and behaves as expected 👍 I found a handful of minor issues, all of which I've added with suggestions in the review comments.

2023-10-03 19:48 UTC, cstephen commented on routes/taspr.py
> +import json
```suggestion
```

The json module is an unused import here.

2023-10-03 19:48 UTC, cstephen commented on templates/documentation/taspr.html
> +
```suggestion
</pre>
```
Just need to close the `<pre>` block here.

2023-10-03 19:48 UTC, cstephen commented on templates/documentation/taspr.html
>  <h4>Yearly values within provided year range (point query)</h4>
```suggestion
<h4>Monthly min, mean, and maximum temperature for each year (point query)</h4>
```
Update this `<h4>` heading to match the corresponding output section.

2023-10-03 19:48 UTC, cstephen commented on routes/taspr.py
> +    #     return render_template("500/server_error.html"), 500
```suggestion
    try:
        point_pkg = asyncio.run(run_fetch_tas_2km_point_data(lat, lon))
    except Exception as exc:
        if hasattr(exc, "status") and exc.status == 404:
            return render_template("404/no_data.html"), 404
        return render_template("500/server_error.html"), 500
```

2023-10-03 19:48 UTC, cstephen commented on routes/eds.py
> +            print(f"Retrying {url} after attempt {retry + 1}")
```suggestion
            app.logger.info(f"Retrying {url} after attempt {retry + 1}")
```

2023-10-04 00:45 UTC, charparr approved these changes
Alright with Craig's suggestions and the most recent commit https://github.com/ua-snap/data-api/pull/357/commits/f569a704dda619012454cc80c1dc6330c76651e0 this is looking good! I've hitting the expected No Data / Invalid Latlon / Bad Request errors and also returning data as expected via routes like http://127.0.0.1:5000/tas2km/point/65.0628/-146.1627 and http://127.0.0.1:5000/eds/all/65/-145.

CSV output looks good for the `tas2km` routes too!

2023-10-04 18:14 UTC, cstephen commented on routes/eds.py
> +            print(f"Retrying {url} after attempt {retry + 1}")
Bruce suggested using `app.logger.warn` instead.

2023-10-04 19:00 UTC, merged