Combined PR for updating data in the API, providing JSON endpoints for that updated data, and functionality for caching the API in Varnish
ua-snap/data-api pull request #86
Opened 2022-02-05 01:17 UTC by BobTorgerson

This PR provides new functionality to the API with several new endpoints.

1.  **/update**
This endpoint will go out to the https://github.com/ua-snap/geospatial-vector-veracity repository to pull down the latest version of the Alaska location's CSV, and the shapefile data for the HUCs and protected areas. Once downloaded, it runs Python code to convert those files into JSON files that can be requested via the next endpoint.

2. **/place**
This endpoint requests a JSON representation of the data collected from the endpoint above. These endpoints should mirror the ones currently found in the IEM webapp: https://github.com/ua-snap/iem-webapp/tree/main/assets

The endpoints available are: /place/communities, /place/hucs, and /place/protected_areas

3. **/cache**
**NOTE:** This endpoint should only be run on the Varnish cache!  
This will query all desired endpoints to pre-populate our cache. It takes the routes from the Flask app and modifies the returned routes to use GET requests to query all communities, HUCs, and protected areas. For any GET request that does not return a 200 HTTP status code, it logs the status code along with the URL that caused it.

Closes #78 
Closes #79

2022-02-07 23:10 UTC, brucecrevensten requested changes
This is great!  I have a couple specific notes and then one high-level thought, would using git submodules instead of doing HTTP fetches work here?  That might be a good way to keep things in sync with less code, but I don't know.  Also can you make a combined `places/all` route?

2022-02-08 18:46 UTC, BobTorgerson commented on routes/vectordata.py
> +    return df.to_json(orient="records")
This has been updated to use the Response() for Flask with MIMETYPE application/json.

2022-02-08 19:07 UTC, BobTorgerson commented on routes/vectordata.py
> +            json.dump(output, outfile)
These files have been removed from the Git repository and have been added to the .gitignore file.

2022-02-08 19:36 UTC, BobTorgerson commented on routes/vectordata.py
> +    if update_data():
Removed conditional response from update_data() and now it doesn't return anything.

2022-02-08 19:37 UTC, BobTorgerson commented on templates/vectordata/failed_update.html
> +{% extends 'base.html' %}
Removed both templates as there are no longer conditional responses. It either errors out if fail, or returns a 200 response with a simple JSON response.

2022-02-08 21:05 UTC, BobTorgerson commented on routes/vectordata.py
> +def get_json_for_type(type):
The /places/all route has been created and will return a combined JSON object of all the communities, HUCs, and protected areas. The JSON fields are differentiated by a key of "type" which is one of three values: ['community', 'huc', or 'protected_area']

2022-02-09 20:25 UTC, BobTorgerson commented on routes/vectordata.py
> +    jsonpath = f"data/jsons/{json_types[type]}"
This has been done by adding the full paths to the luts.py file and querying based on the type variable.

2022-02-10 02:05 UTC, merged